### ISSUE TITLE
tensor4d error

### ISSUE THREAD

**Issue by rahulroxx** [mihaelacr/pydeeplearn#22]
theano version: 0.9 ( bleeding edge )
I ran
` train-emotion-net.py --emotions happy sad --display_example_data --path_to_data . --net_file trained.p`
after creating dataset 
but it throws error

```
RuntimeError: could not set tensor4d descriptor: CUDNN_STATUS_BAD_PARAMshapes=0
2 1 1 strides=2 1 1 1
Apply node that caused the error: GpuDnnSoftmax{tensor_format='bc01', mode='chan
nel', algo='log'}(GpuContiguous.0)
Toposort index: 66
Inputs types: [CudaNdarrayType(float32, (False, False, True, True))]
Inputs shapes: [(0, 2, 1, 1)]
Inputs strides: [(2, 1, 0, 0)]
Inputs values: [CudaNdarray([])]
Outputs clients: [[GpuDimShuffle{0,1}(GpuDnnSoftmax{tensor_format='bc01', mode='
channel', algo='log'}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-tr
ace of when this node was created. This can be done with by setting the Theano f
lag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be
 disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storag
e map footprint of this apply node.
```

**Comment by mihaelacr** [comment]
Hey, thanks for filing this (and sorry for the delay)!

The exact same command works for me, I ran it now with theano 0.8.2 9, but on a CPU. From what I see, you are using a GPU, so this could be CUDA related.

Can you please try the command on a CPU (with 0.9), and see if that works? I will try to get a hand on a GPU in the meantime and update this bug if I am able to run the code using it.

**Comment by mihaelacr** [comment]
Hey!

So the code seems to be working fine for me on a GPU, but without `cuDNN`. `nvidia-smi` is showing that the process is running on GPU, and importing theano returns
`Using gpu device 0: GeForce GTX 980 (CNMeM is disabled, cuDNN not available)`.

So the code is working with theano 0.8.2, on a GPU, but without cuDNN.

**Comment by mihaelacr** [comment]
Update: managed to get the code working with cuDNN too.

I am able to run the code on a GPU, using theano 0.8.2, and cuDNN 5103. Please try using the latest pip version of theano and things should be fine.
